[project]
id = "php-starter"
name = "PHP Starter with Nubo"
version = "1.0.0"

[[build.env]]
name = "BP_PHP_SERVER"
value = "nginx"

[[build.env]]
name = "PORT"
value = "6826"

[[build.env]]
name = 'BP_PHP_WEB_DIR'
value = 'htdocs'
